name: 'Cache and Install Node Dependencies'
description: 'Caches node_modules and installs dependencies if cache is missing'
inputs:
  caching:
    description: 'Where to cache dependecies or not'
    required: true
    default: 'true'
outputs:
  used-cache:
    description: 'Random Number'
    value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
  using: 'composite'
  steps:
    - name: Cache dependencies
      if: inputs.cacing == 'true'
      id: cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}

    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true' || inputs.caching != 'true'
      run: npm ci
      shell: bash
